---
providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: ./zones
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN
  # edgedns:
  #   class: octodns_edgedns.AkamaiProvider
  #   client_secret: env/AKAMAI_CLIENT_SECRET
  #   host: env/AKAMAI_HOST
  #   access_token: env/AKAMAI_ACCESS_TOKEN
  #   client_token: env/AKAMAI_CLIENT_TOKEN

zones:
  freecodecamp.dev.:
    sources:
      - config
      # - cloudflare
    targets:
      - edgedns

  freecodecamp.rocks.:
    sources:
      - config
      # - cloudflare
    targets:
      - edgedns
